### ISSUE TITLE
기본 UI Layout 작업

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#38]

**Comment by kimalec** [comment]
http://www.ionicframework.com/docs/nightly/api/directive/ionScroll/ - chart and table를 위한  scroll example

**Comment by kimalec** [comment]
ion-nav-view의  view-container css 속성에 width, height 100%를 가지고 있음.

layer는  {body: ion-nav-bar, ion-nav-view: {ion-tabs: {div tab-nav, ion-nav-view: {ion-view: {ion-content: {div scroll: { 작성하는 코드}, div scroll-bar} } } }

**Comment by kimalec** [comment]
background에 이미지 깔때 ionic.app.scss에 아래와 같이 추가.
```css
.scroll-content {
  background: url("../img/screen-dash.png");
}
```
