### ISSUE TITLE
시안에서 제안한 폰트 적용

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#49]
한글 Apple 산돌고딕NEO
숫자 Helvetica Neue UltarLight

**Comment by kimalec** [comment]
Apple font는 apple device에서만 사용 가능한듯.

LICENSE AGREEMENT FOR THE APPLE SAN FRANCISCO FONT
For iOS and OS X application uses only

**Comment by kimalec** [comment]
# font type
ttf - truetype
otf - opentype
eot - Embedded OpenType - a compact form of OpenType fonts designed by Microsoft for use as embedded fonts on web pages.
woff - a font format for use in web pages. It was developed during 2009[2] and is now a World Wide Web Consortium (W3C) Recommendation.

**Comment by kimalec** [comment]
```css
@font-face {
  font-family: "helvetica neue ultralight";
  src: url("../fonts/HelveticaNeue-UltraLight.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Nanum Barun Gothic";
  src: url("../fonts/NanumBarunGothic.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}
```
