### ISSUE TITLE
tabs의 border 상단 line 없애기

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#60]
<img width="433" alt="2015-08-23 23 08 30" src="https://cloud.githubusercontent.com/assets/6895272/9428518/a46a7b40-49eb-11e5-916b-47ef92d4bcfd.png">

**Comment by kimalec** [comment]
border를 0px 로만 하면, osx safari와 firefox에서는 정상적으로 없어지는데, iPhone, android에서는 안 없어짐.
```css
//it's not working on webview T.T
.tabs {
  border: 0px;
  border-color: transparent;
  border-top: transparent;
  border-bottom: transparent;
}
```
